# Generated by Django 2.2.6 on 2020-09-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.IntegerField()),
                ('model_name', models.CharField(max_length=70)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom_manager.Showroom')),
            ],
        ),
    ]
